export const sportsList = [
  {label: "golf", value: "Golf"},
  {label: "tennis", value: "Tennis"},
  {label: "cricket", value: "Cricket"},
  {label: "basketball", value: "BasketBall"},
  {label: "baseball", value: "Baseball"},
  {label: "americanfootball", value: "American Football"},
  {label: "aquatics", value: "Aquatics"},
  {label: "archery", value: "Archery"},
  {label: "automobileracing", value: "Automobile Racing"},
  {label: "badminton", value: "Badminton"},
  {label: "beachvolleyball", value: "Beach Volleyball"},
  {label: "bobsleigh", value: "Bobsleigh"},
  {label: "bodybuilding", value: "Body Building"},
  {label: "boxing", value: "Boxing"},
  {label: "crosscountryrunning", value: "Cross Country Running"},
  {label: "crosscountrysking", value: "Cross Country Sking"},
  {label: "curling", value: "Curling"},
  {label: "cycling", value: "Cycling"},
  {label: "darts", value: "Darts"},
  {label: "decathlon", value: "Decathlon"},
  {label: "downhillskiing", value: "Down Hill Skiing"},
  {label: "equestrianism", value: "Equestrianism"},
  {label: "esports", value: "eSports"},
  {label: "fencing", value: "Fencing"},
  {label: "fieldhockey", value: "Field Hockey"},
  {label: "figureskating", value: "Figure Skating"},
  {label: "gymnastics", value: "Gymnastics"},
  {label: "icehokey", value: "Ice Hokey"},
  {label: "martialarts", value: "Martial Arts"},
  {label: "mixedmartialarts", value: "Mixed Martial Arts"},
  {label: "modernpentathlon", value: "Modern Pentathlon"},
  {label: "motorcycleracing", value: "Motorcycle Racing"},
  {label: "netball", value: "Netball"},
  {label: "polo", value: "Polo"},
  {label: "racquetball", value: "Racquetball"},
  {label: "rowing", value: "Rowing"},
  {label: "rugby", value: "Rugby"},
  {label: "sailing", value: "Sailing"},
  {label: "softball", value: "Softball"},
  {label: "shooting", value: "Shooting"},
  {label: "skateboarding", value: "Skateboarding"},
  {label: "skeetshooting", value: "Skeet Shooting"},
  {label: "skeleton", value: "Skeleton"},
  {label: "snowboarding", value: "Snow Boarding"},
  {label: "soccer", value: "Soccer (Football)"},
  {label: "squash", value: "Squash"},
  {label: "sencing", value: "Surfing"},
  {label: "swimming", value: "Swimming"},
  {label: "trackandfield", value: "Track and Field"},
];
